site_name: Andrew D. Orlov
nav:
  - Curriculum Vitae: index.md
  - Sample Documentation Display:
    - BookStack:
      - Technical Architecture: BookStackTA.md
      - Support Procedures: BookStackSP.md
      - User Guide: BookStackUG.md
theme:
  name: readthedocs
  custom_dir: overrides
  navigation_depth: 6

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - scripts/extra.js
  
markdown_extensions:
  - attr_list
  - pymdownx.details